feeds:
  - http://www.khan.co.kr/rss/rssdata/it_news.xml
  - https://newsis.com/RSS/health.xml
  - https://www.mediatoday.co.kr/rss/S1N7.xml
  - http://www.womennews.co.kr/rss/S1N39.xml
  - https://www.hani.co.kr/rss/science/
